### ISSUE TITLE
nsslapd-minssf - Default setting

### ISSUE THREAD

**Issue by GuardMoony** [spacepants/puppet-ds_389#2]
Hi,

The default setting for nsslapd-minssf provided bij 389 Directory Server is 0
But your template is using a default of 128. This means that only secured connection with a higher encryption then 128 is supported.
 I would suggest to add a new variable and change the template to use the variable instead of using a static value.
nsslapd-minssf: 128

Information: http://www.port389.org/docs/389ds/howto/howto-use-ssf-restrictions.html#minimum-ssf-usage

Patch:
[minssf.patch.txt](https://github.com/spacepants/puppet-ds_389/files/1591266/minssf.patch.txt)

**Comment by spacepants** [comment]
Sure, I can parameterize that. Didn't think ldap:// connections without StartTLS was a use case people still had these days.

**Comment by GuardMoony** [comment]
thx,
Its mainly to keep inline with the defaults provided by the software, and have the ability to change this.
